/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequest } from '../model/models';
import { LoginResponse } from '../model/models';
import { RegisterRequest } from '../model/models';
import { RegisterResponse } from '../model/models';
import { UpdateUser400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface LoginRequestParams {
    loginRequest: LoginRequest;
}

export interface RegisterRequestParams {
    registerRequest: RegisterRequest;
}


export interface AuthenticationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    login(requestParameters: LoginRequestParams, extraHttpRequestParams?: any): Observable<LoginResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    register(requestParameters: RegisterRequestParams, extraHttpRequestParams?: any): Observable<RegisterResponse>;

}
