/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateBrandRequest } from '../model/models';
import { CreateBrandResponse } from '../model/models';
import { GetAllBrandResponse } from '../model/models';
import { GetBrandByIdResponse } from '../model/models';
import { Update400Response } from '../model/models';
import { UpdateBrandRequest } from '../model/models';
import { UpdateBrandResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface Add4RequestParams {
    createBrandRequest: CreateBrandRequest;
}

export interface Delete4RequestParams {
    id: number;
}

export interface GetBrandByIdRequestParams {
    id: number;
}

export interface Update4RequestParams {
    updateBrandRequest: UpdateBrandRequest;
}


export interface BrandControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    add4(requestParameters: Add4RequestParams, extraHttpRequestParams?: any): Observable<CreateBrandResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    delete4(requestParameters: Delete4RequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAll4(extraHttpRequestParams?: any): Observable<Array<GetAllBrandResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getBrandById(requestParameters: GetBrandByIdRequestParams, extraHttpRequestParams?: any): Observable<GetBrandByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    update4(requestParameters: Update4RequestParams, extraHttpRequestParams?: any): Observable<UpdateBrandResponse>;

}
