/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CreateCarRequest } from '../model/models';
import { CreateCarResponse } from '../model/models';
import { GetAllCarResponse } from '../model/models';
import { GetCarByIdResponse } from '../model/models';
import { Update400Response } from '../model/models';
import { UpdateCarRequest } from '../model/models';
import { UpdateCarResponse } from '../model/models';

import { Configuration } from '../configuration';

export interface Add3RequestParams {
  createCarRequest: CreateCarRequest;
}

export interface Delete3RequestParams {
  id: number;
}

export interface GetCarByIdRequestParams {
  id: number;
}

export interface Update3RequestParams {
  updateCarRequest: UpdateCarRequest;
}

export interface CarControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param requestParameters
   */
  add3(
    requestParameters: Add3RequestParams,
    extraHttpRequestParams?: any
  ): Observable<CreateCarResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  delete3(
    requestParameters: Delete3RequestParams,
    extraHttpRequestParams?: any
  ): Observable<{}>;

  /**
   *
   *
   */
  getAll3(extraHttpRequestParams?: any): Observable<Array<GetAllCarResponse>>;

  /**
   *
   *
   * @param requestParameters
   */
  getCarById(
    requestParameters: GetCarByIdRequestParams,
    extraHttpRequestParams?: any
  ): Observable<GetCarByIdResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  update3(
    requestParameters: Update3RequestParams,
    extraHttpRequestParams?: any
  ): Observable<UpdateCarResponse>;
}
