/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CreateCarRequest } from '../model/models';
import { CreateCarResponse } from '../model/models';
import { GetAllCarResponse } from '../model/models';
import { GetCarByIdResponse } from '../model/models';
import { UpdateCarRequest } from '../model/models';
import { UpdateCarResponse } from '../model/models';
import { UpdateUser400Response } from '../model/models';

import { Configuration } from '../configuration';

export interface CreateCarRequestParams {
  createCarRequest: CreateCarRequest;
}

export interface DeleteCarRequestParams {
  id: number;
}

export interface GetCarByIdRequestParams {
  id: number;
}

export interface UpdateCarRequestParams {
  updateCarRequest: UpdateCarRequest;
}

export interface CarControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param requestParameters
   */
  createCar(
    requestParameters: CreateCarRequestParams,
    extraHttpRequestParams?: any
  ): Observable<CreateCarResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  deleteCar(
    requestParameters: DeleteCarRequestParams,
    extraHttpRequestParams?: any
  ): Observable<{}>;

  /**
   *
   *
   */
  getAllCars(
    extraHttpRequestParams?: any
  ): Observable<Array<GetAllCarResponse>>;

  /**
   *
   *
   * @param requestParameters
   */
  getCarById(
    requestParameters: GetCarByIdRequestParams,
    extraHttpRequestParams?: any
  ): Observable<GetCarByIdResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  updateCar(
    requestParameters: UpdateCarRequestParams,
    extraHttpRequestParams?: any
  ): Observable<UpdateCarResponse>;
}
