/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateCreditCardRequest } from '../model/models';
import { CreateCreditCardResponse } from '../model/models';
import { GetAllCreditCardResponse } from '../model/models';
import { GetCreditCardByIdResponse } from '../model/models';
import { UpdateCreditCardRequest } from '../model/models';
import { UpdateCreditCardResponse } from '../model/models';
import { UpdateUser400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateCreditCardRequestParams {
    createCreditCardRequest?: CreateCreditCardRequest;
}

export interface DeleteCreditCardRequestParams {
    id: number;
}

export interface GetCreditCardByIdRequestParams {
    id: number;
}

export interface UpdateCreditCardRequestParams {
    updateCreditCardRequest?: UpdateCreditCardRequest;
}


export interface CreditCardControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createCreditCard(requestParameters: CreateCreditCardRequestParams, extraHttpRequestParams?: any): Observable<CreateCreditCardResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteCreditCard(requestParameters: DeleteCreditCardRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllCreditCards(extraHttpRequestParams?: any): Observable<Array<GetAllCreditCardResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getCreditCardById(requestParameters: GetCreditCardByIdRequestParams, extraHttpRequestParams?: any): Observable<GetCreditCardByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateCreditCard(requestParameters: UpdateCreditCardRequestParams, extraHttpRequestParams?: any): Observable<UpdateCreditCardResponse>;

}
