/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CreateFuelRequest } from '../model/models';
import { CreateFuelResponse } from '../model/models';
import { GetAllFuelResponse } from '../model/models';
import { GetFuelByIdResponse } from '../model/models';
import { Update400Response } from '../model/models';
import { UpdateFuelRequest } from '../model/models';
import { UpdateFuelResponse } from '../model/models';

import { Configuration } from '../configuration';

export interface Add2RequestParams {
  createFuelRequest: CreateFuelRequest;
}

export interface Delete2RequestParams {
  id: number;
}

export interface GetFuelByIdRequestParams {
  id: number;
}

export interface Update2RequestParams {
  updateFuelRequest: UpdateFuelRequest;

  /**
   *
   *
   * @param requestParameters
   */
  add2(
    requestParameters: Add2RequestParams,
    extraHttpRequestParams?: any
  ): Observable<CreateFuelResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  delete2(
    requestParameters: Delete2RequestParams,
    extraHttpRequestParams?: any
  ): Observable<{}>;

  /**
   *
   *
   */
  getAll2(extraHttpRequestParams?: any): Observable<Array<GetAllFuelResponse>>;

  /**
   *
   *
   * @param requestParameters
   */
  getFuelById(
    requestParameters: GetFuelByIdRequestParams,
    extraHttpRequestParams?: any
  ): Observable<GetFuelByIdResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  update2(
    requestParameters: Update2RequestParams,
    extraHttpRequestParams?: any
  ): Observable<UpdateFuelResponse>;
}
