/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateFuelRequest } from '../model/models';
<<<<<<< HEAD
import { CreateFuelResponse } from '../model/models';
import { GetAllFuelResponse } from '../model/models';
import { GetFuelByIdResponse } from '../model/models';
import { Update400Response } from '../model/models';
=======
import { CreatedFuelResponse } from '../model/models';
import { GetAllFuelResponse } from '../model/models';
import { GetFuelByIdResponse } from '../model/models';
import { GetTransmissionById400Response } from '../model/models';
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd
import { UpdateFuelRequest } from '../model/models';
import { UpdateFuelResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


<<<<<<< HEAD
export interface Add2RequestParams {
    createFuelRequest: CreateFuelRequest;
}

export interface Delete2RequestParams {
    id: number;
}

=======
export interface CreateFuelRequestParams {
    createFuelRequest: CreateFuelRequest;
}

>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd
export interface GetFuelByIdRequestParams {
    id: number;
}

<<<<<<< HEAD
export interface Update2RequestParams {
=======
export interface UpdateFuelByIdRequestParams {
    id: number;
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd
    updateFuelRequest: UpdateFuelRequest;
}


export interface FuelControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
<<<<<<< HEAD
    add2(requestParameters: Add2RequestParams, extraHttpRequestParams?: any): Observable<CreateFuelResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    delete2(requestParameters: Delete2RequestParams, extraHttpRequestParams?: any): Observable<{}>;
=======
    createFuel(requestParameters: CreateFuelRequestParams, extraHttpRequestParams?: any): Observable<CreatedFuelResponse>;
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd

    /**
     * 
     * 
*/
<<<<<<< HEAD
    getAll2(extraHttpRequestParams?: any): Observable<Array<GetAllFuelResponse>>;
=======
    getAllFuels(extraHttpRequestParams?: any): Observable<Array<GetAllFuelResponse>>;
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd

    /**
     * 
     * 
* @param requestParameters
     */
    getFuelById(requestParameters: GetFuelByIdRequestParams, extraHttpRequestParams?: any): Observable<GetFuelByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
<<<<<<< HEAD
    update2(requestParameters: Update2RequestParams, extraHttpRequestParams?: any): Observable<UpdateFuelResponse>;
=======
    updateFuelById(requestParameters: UpdateFuelByIdRequestParams, extraHttpRequestParams?: any): Observable<UpdateFuelResponse>;
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd

}
