/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import { CreateTransmissionRequest } from '../model/models';
import { CreateTransmissionResponse } from '../model/models';
import { GetAllTransmissionResponse } from '../model/models';
import { GetTransmissionByIdResponse } from '../model/models';
import { Update400Response } from '../model/models';
import { UpdateTransmissionRequest } from '../model/models';
import { UpdateTransmissionResponse } from '../model/models';

import { Configuration } from '../configuration';

export interface DeleteRequestParams {
  id: number;
}

export interface AddRequestParams {
  createTransmissionRequest: CreateTransmissionRequest;
}

export interface GetTransmissionByIdRequestParams {
  id: number;
}

export interface UpdateRequestParams {
  updateTransmissionRequest: UpdateTransmissionRequest;
}

export interface TransmissionControllerServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   *
   * @param requestParameters
   */
  _delete(
    requestParameters: DeleteRequestParams,
    extraHttpRequestParams?: any
  ): Observable<{}>;

  /**
   *
   *
   * @param requestParameters
   */
  add(
    requestParameters: AddRequestParams,
    extraHttpRequestParams?: any
  ): Observable<CreateTransmissionResponse>;

  /**
   *
   *
   */
  getAll(
    extraHttpRequestParams?: any
  ): Observable<Array<GetAllTransmissionResponse>>;

  /**
   *
   *
   * @param requestParameters
   */
  getTransmissionById(
    requestParameters: GetTransmissionByIdRequestParams,
    extraHttpRequestParams?: any
  ): Observable<GetTransmissionByIdResponse>;

  /**
   *
   *
   * @param requestParameters
   */
  update(
    requestParameters: UpdateRequestParams,
    extraHttpRequestParams?: any
  ): Observable<UpdateTransmissionResponse>;
}
