/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserRequest } from '../model/models';
import { CreateUserResponse } from '../model/models';
import { GetAllUserResponse } from '../model/models';
import { GetUserByIdResponse } from '../model/models';
import { UpdateUser400Response } from '../model/models';
import { UpdateUserRequest } from '../model/models';
import { UpdateUserResponse } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateUserRequestParams {
    createUserRequest: CreateUserRequest;
}

export interface DeleteUserRequestParams {
    id: number;
}

export interface GetUserByIdRequestParams {
    id: number;
}

export interface UpdateUserRequestParams {
    updateUserRequest: UpdateUserRequest;
}


export interface UserControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createUser(requestParameters: CreateUserRequestParams, extraHttpRequestParams?: any): Observable<CreateUserResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteUser(requestParameters: DeleteUserRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllUsers(extraHttpRequestParams?: any): Observable<Array<GetAllUserResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getUserById(requestParameters: GetUserByIdRequestParams, extraHttpRequestParams?: any): Observable<GetUserByIdResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateUser(requestParameters: UpdateUserRequestParams, extraHttpRequestParams?: any): Observable<UpdateUserResponse>;

}
