/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateTransmissionRequest { 
<<<<<<< HEAD
    name: string;
=======
    name?: string;
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd
}

