/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
<<<<<<< HEAD
 *
=======
 * 
>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

<<<<<<< HEAD
export interface UpdateBrandRequest {
  id?: number;
  name: string;
}
=======

export interface UpdateBrandRequest { 
    name?: string;
}

>>>>>>> a055835ee9b8b7dbcc6674a078e2feb94a320cfd
